services:
  app:
    image: clothing-store
    build:
      context: .
    container_name: ps-app-clothing-store
    depends_on:
      - db
      - front
    networks:
      - ps
    ports:
      - "8080:8080"
  front:
    image: prod-front
    container_name: ps-front
    networks:
      - ps
    ports:
      - "80:80"
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps
networks:
  ps:
